#!/bin/bash

function usage() {
	echo ""
	echo "git undo"
	echo ""
	echo "  See 'man git-undo' for further information"
	echo ""
}

function commit() {
	echo "Undoing latest commit"
	git reset --soft HEAD^
}

function stash() {
	echo "Unapplying stash"
	git stash show -p | git apply -R
}

function pushedmerge() {
	git revert -m 1 $1
}


if [ "$1" == "commit" ]; then
	commit
elif [ "$1" == "stash-apply" ]; then
	stash
elif [ "$1" == "pushed-merge" ]; then
	pushedmerge $2 
else
	usage
fi
